server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: 10111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
    show-sql: true
